env:
  browser: true
  es6: true
  node: true
extends: 'airbnb'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  camelcase: 1
  function-paren-newline: 1
  func-names: 0
  max-len: [2, 100, 2, { ignoreUrls: true, ignoreComments: false, ignorePattern: "^(import|\\s+\\w+?: |\\s+\\w+? \\w+? = )" }]
  no-shadow: 1
  no-unexpected-multiline: 2
  object-curly-newline: 0
  operator-linebreak: 0
  padded-blocks: ["error", "never"]
  prefer-destructuring: 1
  semi: [2, never]
  sort-vars: 1
  sort-keys: 1
  no-mixed-operators:
    - 'warn'
  no-underscore-dangle: 0

  import/extensions: 0
  import/imports-first: 2
  import/named: 2
  import/no-commonjs: 0
  import/no-cycle: 1
  import/no-duplicates: 2
  import/no-named-as-default: 1
  import/no-unresolved: 2
  import/prefer-default-export: 1
  import/no-extraneous-dependencies:
    - 'error'
    - devDependencies: true

  jsx-a11y/accessible-emoji: 1
  jsx-a11y/alt-text: 1
  jsx-a11y/anchor-is-valid: 1
  jsx-a11y/click-events-have-key-events: 1
  jsx-a11y/img-has-alt: 0
  jsx-a11y/label-has-for: 1
  jsx-a11y/media-has-caption: 1
  jsx-a11y/mouse-events-have-key-events: 1
  jsx-a11y/no-autofocus: 0
  jsx-a11y/no-static-element-interactions: 1

  react/button-has-type: 1
  react/default-props-match-prop-types: 1
  react/destructuring-assignment: 1
  react/display-name: 1
  react/forbid-component-props: 1
  react/forbid-prop-types: 1
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-key: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-wrap-multilines: 1 # TODO: Finetune this
  react/no-access-state-in-setstate: 1
  react/no-string-refs: 2
  react/no-unescaped-entities: 0 # very unlikely to cause issues, very annoying to have on.
  react/prop-types: 1 # TODO: ESLint enforce propTypes #2970
  react/require-default-props: 1
  react/sort-comp: 1 # Enforce component methods order (fixable)
  react/sort-prop-types: 1 # Enforce propTypes declarations alphabetical sorting
  react/style-prop-object: 1 # Enforce style prop value being an object
